//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Project.Models
{
    using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Informaion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informaion()
        {
            this.projects = new HashSet<project>();
        }
        public int IdUser { get; set; }
        public string IdASP { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First name must only contain letters.")]

        public string FirstName { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Last name must only contain letters.")]

        public string LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = " Nationality must only contain letters.")]

        public string Ntionality { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> JobTitle { get; set; }
        [Required]

        public string Img { get; set; }
        [Required]

        public string CV { get; set; }
        public Nullable<int> University { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First name must only contain letters.")]

        public string Major { get; set; }
        public Nullable<System.DateTime> GradDate { get; set; }
        [Required]

        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First name must only contain letters.")]

        public string About { get; set; }
        [Required]

        public string Skills { get; set; }

        public Nullable<int> CityInfo { get; set; }
        [Required]

        public string Github { get; set; }
        [Required]
        [RegularExpression(@"^(077|078|079)\d{7}$", ErrorMessage = "Please enter a valid phone number starting with 077, 078, or 079 and with a total of 10 digits")]

        public string Phone { get; set; }
        [Required]

        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First name must only contain letters.")]

        public string Experiences { get; set; }
        [Required]

        public Nullable<System.DateTime> LogInDate { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<bool> IsPayed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
        public virtual Job Job { get; set; }
        public virtual University University1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
    }
}
