//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Project.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class project
    {
        public int IdProject { get; set; }
        public Nullable<int> IdUserProject { get; set; }


        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Project name must only contain letters.")]


        public string ProjectName { get; set; }

        public string ProjectLink { get; set; }
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = " Techniques must only contain letters.")]

        public string techniques { get; set; }
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = " About Project must only contain letters.")]

        public string AboutProject { get; set; }

        public Nullable<bool> ProjectType { get; set; }
    
        public virtual Informaion Informaion { get; set; }
    }
}
